name: CI – Lint and Validate

on:
  pull_request:
    branches: [main]
  pull_request:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linters
      run: |
        pip install black flake8 isort

    - name: Run Black
      run: black --check app/

    - name: Run Flake8
      run: flake8 app/

    - name: Run isort
      run: isort --check-only app/

    - name: Validate Terraform
      run: |
        cd terraform
        terraform init -backend=false
        terraform validate
